#!/bin/sh
BAT_THEME="Solarized (light)"

batorcat() {
    file="$1"
    shift
    if command -v bat >/dev/null 2>&1; then
        bat --color=always --theme="$BAT_THEME" --style=numbers --pager=never "$file" "$@"
    else
        cat "$file"
    fi
}

image() {
    if [ -n "$WT_SESSION" ] || [ -n "$TMUX" ]; then
      # windows terminal (no sixels yet) or tmux (not much success with passthrough to iterm here)
      chafa -f symbols -s "$3x$4" --animate off --polite on "$1"
    else
      chafa -f sixels -s "$3x$4" --animate off --polite on "$1"
    fi
}

CACHE="$HOME/.cache/lf/thumbnail.$(sha256sum "$1" | awk '{print $1}')"

case "$(file -Lb --mime-type -- "$1")" in
    image/*)
        chafa -f sixels -s "${2}x${3}" --animate off --polite on "$1"
        exit 1
        ;;
    application/pdf)
        [ ! -f "${CACHE}.jpg" ] && pdftoppm -jpeg -f 1 -singlefile "$1" "$CACHE"
        image "${CACHE}.jpg" "$2" "$3" "$4" "$5"
        ;;
    text/*|application/json)
        batorcat "$1"
        exit 0
        ;;
    *)
    lesspipe "$1" || batorcat "$1"
    ;;
esac
