[mgr]
prepend_keymap = [
  { on = "<C-q>", run = "close", desc = "Quit current tab" },
  { on = "l", run = "plugin smart-enter", desc = "Enter the child directory, or open the file" },
  { on = "t", run = "shell --block $SHELL", desc = "Open terminal" },
  { on = [ "f" ], run = [ "plugin jump-to-char" ], desc = "Jump to first occurrence of character" },
  { on = [ "F" ], run = [ "plugin jump-to-char previous" ], desc = "Jump to first occurrence of character" },
  { on = ["g", "s"], run = "plugin flash", desc = "Flash Search" },
  { on = [ "T" ], run = "plugin toggle-pane max-preview", desc = "Maximize or restore the preview pane"},

]
