[mgr]
prepend_keymap = [
  { on = "<C-q>", run = "close", desc = "Quit current tab" },
  { on = "l", run = "plugin smart-enter", desc = "Enter the child directory, or open the file" },
  { on = "t", run = "shell --block $SHELL", desc = "Open terminal" },
  { on = [ "f" ], run = [ "plugin jump-to-char" ], desc = "Jump to first occurrence of character" },
  { on = [ "F" ], run = [ "plugin jump-to-char previous" ], desc = "Jump to first occurrence of character" },
  { on = ["g", "s"], run = "plugin flash", desc = "Flash Search" },
  { on = [ "T" ], run = "plugin toggle-pane max-preview", desc = "Maximize or restore the preview pane"},
  { on = "u", run = "plugin restore", desc = "Restore last deleted files/folders" },
    # Select files/folders to restore. Input item index or range separated by comma:
    # - Restore a trashed file:
    #      What file to restore [0..4]: 4
    # - Restore multiple trashed files separated by comma, also support range:
    #      What file to restore [0..3]: 0-2, 3

    # If you remove --overwrite it will exit without restore when there is existed file.
    { on = "U", run = "shell --block -- clear && trash-restore --overwrite", desc = "Restore deleted file (Interactive)" },
]
