#! /bin/sh

### Variables ###

export TERMINAL=alacritty
export BROWSER=zen-browser
export FILE_MANAGER=thunar

### Output ###
bspc monitor VGA-1 -d 1 2 3 4 5
bspc monitor HDMI-1 -d 6 7 8 9 0

### Rules/EnvVars ###
gsettings set org.gnome.desktop.interface gtk-theme 'Adwaita-dark'
gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'

systemctl --user import-environment DISPLAY XAUTHORITY GTK_THEME VISUAL EDITOR XDG_CURRENT_DESKTOP
systemctl --user start bspwm-session.target
dbus-update-activation-environment --systemd GTK_THEME VISUAL EDITOR XDG_CURRENT_DESKTOP=bspwm

bspc rule -a Rofi state=floating center=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

### Visual ###
# Borders
bspc config border_width 1
bspc config window_gap 6
bspc config split_ratio 0.50

# Colors
# Focused
bspc config focused_border_color "#ffffff"
# Normal/Unfocused
bspc config normal_border_color "#595959"
# Urgent
bspc config urgent_border_color "#9b0000"

# Focus
bspc config focus_follows_pointer true
bspc config pointer_follows_focus true
bspc config pointer_follows_monitor true
bspc config pointer_modifier mod4

# Keep monitor on, it will be managed by the idle script.
xset -dpms s off

### Other ###
# Repeat delay 300ms and rate 75ms
xset r rate 300 75

# Mouse acceleration
xset m 0 0
xinput set-prop "pointer:Compx 2.4G Wireless Receiver" "libinput Accel Profile Enabled" 0 1 0

# Cursor
xsetroot -cursor_name left_ptr

# Layout
setxkbmap -layout us -option caps:none

# idk
bspc config borderless_monocle true
bspc config gapless_monocle true

### Startup ###
# SXHKD for Keys
pgrep -x sxhkd >/dev/null || sxhkd &

# Feh for Wallpapers
feh --bg-fill ~/.config/Wallpaper.jpg &

# Polybar
~/.config/polybar/launch.sh &

# Idle
~/.config/bspwm/scripts/idle.sh &
